import SearchCard from "@/components/Search/Card";
import SearchHeader from "@/components/Search/Header";
import SearchSidebar from "@/components/Search/Sidebar";

export const metadata = {
  title: "Search Tables | OpenTable",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <SearchHeader />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SearchSidebar />
        <div className="w-5/6">
          <SearchCard />
        </div>
      </div>
    </>
  );
}
